name: Phase 1 - GitHub Connection Test

on:
  push:
    branches: [ "main" ]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "GitHub Actions is successfully connected to Shivam's Bike Rental Project!"